### PR TITLE
Update CodeNarcMojo.groovy

### PR DESCRIPTION
**Pull request by jshipman42**
add support for user defined dependencies to be included in classpath of CodeNarc ant task

### CODE REVIEW

**Comment by jshipman42** [comment]
This should resolve Issue #16 No way to provide own rules as classpath resources

**Review by gleclaire — CHANGES_REQUESTED** [review]
Please only submit code changes.  It is too hard to see through all the formatting changes.

**Comment by jshipman42** [comment]
my apologies.  Updated with formatting changes removed.

**Comment by jshipman42** [comment]
There has been no response to this for 3+ months.  Please advise.

**Comment by jshipman42** [comment]
There has been no response for several months now.  Closing this pull request and starting over.

**Pull request closed without merging**
